import {
  Activity,
  Compass,
  Calendar,
  CalendarCheck,
  CalendarClock,
  ClipboardList,
  Receipt as ReceiptIcon,
  Ghost as GhostIcon,
  Database,
  Radio,
  Brain,
  BookOpen,
  HeartPulse,
  Building,
  Server,
  Terminal,
  Bot,
  BotMessageSquare,
  Microscope,
  BarChart3,
  Code2,
  Hammer,
  GitPullRequest,
  Wallet,
  TrendingUp,
  Handshake,
  Scale,
  Shield,
  ShieldCheck,
  KeyRound,
  Plug,
  ChartSpline,
  Settings,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "./types";

const MAP: Record<string, LucideIcon> & Record<IconName, LucideIcon> = {
  activity: Activity,
  compass: Compass,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "clipboard-list": ClipboardList,
  receipt: ReceiptIcon,
  ghost: GhostIcon,
  database: Database,
  radio: Radio,
  brain: Brain,
  "book-open": BookOpen,
  "heart-pulse": HeartPulse,
  building: Building,
  server: Server,
  terminal: Terminal,
  bot: Bot,
  "bot-message-square": BotMessageSquare,
  microscope: Microscope,
  chart: BarChart3,
  "code-2": Code2,
  hammer: Hammer,
  "git-pull-request": GitPullRequest,
  wallet: Wallet,
  "trending-up": TrendingUp,
  handshake: Handshake,
  scale: Scale,
  shield: Shield,
  "shield-check": ShieldCheck,
  "key-round": KeyRound,
  plug: Plug,
  "calendar-clock": CalendarClock,
  "chart-spline": ChartSpline,
  settings: Settings,
};

export function NavIcon({
  name,
  className,
}: {
  name: IconName;
  className?: string;
}) {
  const Cmp = MAP[name];
  return <Cmp className={className} strokeWidth={1.5} />;
}
