// STUB DATA. Used only for visual rendering. Not authoritative.
// Backend will replace via real endpoints. Marked clearly here.
import type {
  AddressItem,
  Agent,
  Appointment,
  BudgetCategory,
  CareItem,
  CleaningEntry,
  ConnectionItem,
  CorrespondenceItem,
  CostRecord,
  DocumentItem,
  EnforcementRule,
  FinanceRecord,
  GateDecisionRecord,
  GentleAlertItem,
  Ghost,
  HumanCheckIn,
  KnowledgeItem,
  LLMItem,
  LegalRecord,
  Machine,
  MaintenanceTask,
  PhysicalAsset,
  PolicyItem,
  Receipt,
  RegistryEntity,
  ReviewItem,
  RoutineEntry,
  RuntimeRecord,
  Schedule,
  SecretReference,
  Sensor,
  SpaceObservation,
  SpendingEvent,
  SupplyEntry,
  SupplyNeed,
  VendorItem,
  Workorder,
} from "../types";
import type { RegistryTypeSummary } from "../components/domain-composition";

export const STUB_REGISTRY_TYPES: RegistryTypeSummary[] = [
  {
    id: "machine",
    label: "Machines",
    description: "LAB 8GB, LAB 512 e LAB 256; ambientes físicos de execução.",
    count: 3,
  },
  {
    id: "sensor",
    label: "Sensors",
    description: "Fontes proprietárias de inteligência: vivos, silenciosos e candidatos.",
    count: 4,
  },
  {
    id: "human",
    label: "Human",
    description: "Pessoas e presença operacional humana.",
    count: 1,
  },
  {
    id: "llm",
    label: "LLMs",
    description: "Tradutores, minis, operators, premium e modelos locais.",
    count: 2,
  },
  {
    id: "runtime",
    label: "Runtimes",
    description: "Software oficial instalado e observado nos LABs.",
    count: 3,
  },
  {
    id: "service",
    label: "Services",
    description: "Supabase, Doppler, Cloudflare e outros provedores materiais.",
    count: 2,
  },
];

export const STUB_ENTITIES: RegistryEntity[] = [
  {
    id: "ent_lab256",
    name: "LAB 256",
    entity_type: "machine",
    domain: "laboratorio.santo-andre",
    role: "workbench",
    status: "active",
    updated_at: "2026-05-19 09:00",
  },
  {
    id: "ent_lab512",
    name: "LAB 512",
    entity_type: "machine",
    domain: "laboratorio.santo-andre",
    role: "inference",
    status: "active",
    updated_at: "2026-05-19 09:00",
  },
  {
    id: "ent_lab8gb",
    name: "LAB 8GB",
    entity_type: "machine",
    domain: "laboratorio.santo-andre",
    role: "supervisor",
    status: "active",
    updated_at: "2026-05-19 09:00",
  },
  {
    id: "ent_dan",
    name: "Dan Voulez",
    entity_type: "human",
    domain: "human",
    role: "operator / consequence signer",
    status: "active",
    updated_at: "2026-05-19 09:00",
  },
  {
    id: "ent_temp_a",
    name: "temp_sensor_a",
    entity_type: "sensor",
    domain: "laboratorio.santo-andre",
    role: "environmental",
    status: "active",
    updated_at: "2026-05-19 08:11",
  },
  {
    id: "ent_door",
    name: "door_contact_main",
    entity_type: "sensor",
    domain: "laboratorio.santo-andre",
    role: "access",
    status: "draft",
    updated_at: "2026-05-19 08:42",
  },
  {
    id: "ent_ollama",
    name: "Ollama LAB 512",
    entity_type: "runtime",
    domain: "runtimes",
    role: "local inference",
    status: "active",
    updated_at: "2026-05-19 08:44",
  },
  {
    id: "ent_local_operator",
    name: "Local Registry Operator",
    entity_type: "llm",
    domain: "llms",
    role: "registry translator",
    status: "active",
    updated_at: "2026-05-19 08:51",
  },
  {
    id: "ent_supabase",
    name: "supabase.prod",
    entity_type: "service",
    domain: "infra",
    role: "online database",
    status: "active",
    updated_at: "2026-05-19 03:14",
  },
];

export const STUB_GHOSTS: Ghost[] = [
  {
    id: "g_001",
    summary: "limpeza do Laboratório Santo Andre não foi comprovada",
    reason: "missing_evidence",
    missing: ["confirmed_by", "evidence_payload"],
    status: "open",
    created_at: "2026-05-19 07:42",
  },
  {
    id: "g_002",
    summary: "compra de filtro HEPA sem recibo anexado",
    reason: "missing_attachment",
    missing: ["evidence_payload", "vendor"],
    status: "open",
    created_at: "2026-05-18 17:08",
  },
  {
    id: "g_003",
    summary: "rotina matinal — humano não confirmou presença",
    reason: "human_unconfirmed",
    missing: ["confirmed_by"],
    status: "open",
    created_at: "2026-05-19 06:30",
  },
  {
    id: "g_004",
    summary: "door_contact_main apareceu nos dados mas não fechou Registry",
    reason: "missing_registry_entity",
    missing: ["registry_entity", "role"],
    status: "open",
    created_at: "2026-05-19 08:42",
  },
];

export const STUB_RECEIPTS: Receipt[] = [
  {
    id: "r_101",
    scope: "lab-routine · backup nightly",
    evidence_summary:
      "supabase.prod snapshot completou em 8m22s, digest registrada.",
    closed_at: "2026-05-19 03:14",
    status: "closed",
    digest: "sha256:9b1c…f2a7",
  },
  {
    id: "r_102",
    scope: "registry · cadastro de sensor temp_sensor_a",
    evidence_summary: "entidade criada online; link com LAB 256 confirmado.",
    closed_at: "2026-05-19 08:11",
    status: "closed",
    digest: "sha256:01ee…8c44",
  },
  {
    id: "r_103",
    scope: "workorder · troca de cabo HDMI",
    evidence_summary: "foto antes/depois anexada por humano.",
    closed_at: "2026-05-18 21:50",
    status: "closed",
    digest: "sha256:4f7d…aa10",
  },
  {
    id: "r_104",
    scope: "machines · LAB 512 heartbeat",
    evidence_summary: "heartbeat recebido, wifi ok e Ollama respondendo health check.",
    closed_at: "2026-05-19 09:01",
    status: "closed",
    digest: "sha256:c021…a551",
  },
];

export const STUB_MACHINES: Machine[] = [
  {
    id: "lab-8gb",
    label: "LAB 8GB",
    role: "supervisor",
    status: "online",
    wifi_status: "wifi · 5 GHz · strong",
    last_boot: "2026-05-18 22:10",
    last_access: "Dan · local shell · 2026-05-18 22:30",
    current_job: "health loop",
    efficiency: "92%",
    maintenance: "sem manutenção pendente",
    security: "sem evento crítico",
    last_heartbeat: "2026-05-19 09:01:12",
    jobs: ["health loop", "recovery check", "heartbeat receipt bridge"],
    runtimes: ["minilab-agent", "heartbeat-daemon"],
  },
  {
    id: "lab-512",
    label: "LAB 512",
    role: "inference",
    status: "online",
    wifi_status: "ethernet · stable",
    last_boot: "2026-05-19 06:05",
    last_access: "local operator · 2026-05-19 08:49",
    current_job: "local registry operator",
    efficiency: "81%",
    maintenance: "model cache approaching limit",
    security: "normal",
    last_heartbeat: "2026-05-19 09:01:14",
    jobs: ["Ollama health check", "registry proposal classifier", "embedding refresh"],
    runtimes: ["Ollama", "local-operator", "benchmark-runner"],
  },
  {
    id: "lab-256",
    label: "LAB 256",
    role: "workbench",
    status: "degraded",
    wifi_status: "wifi · intermittent",
    last_boot: "2026-05-19 07:12",
    last_access: "Dan · browser automation · 2026-05-19 08:58",
    current_job: "manual workbench",
    efficiency: "64%",
    maintenance: "wifi observed intermittent; inspect router position",
    security: "last access expected",
    last_heartbeat: "2026-05-19 08:58:07",
    jobs: ["browser session", "visual inspection", "manual tests"],
    runtimes: ["browser automation", "minilab-ui", "git"],
  },
];

export const STUB_SENSORS: Sensor[] = [
  {
    id: "s_temp_a",
    name: "temp_sensor_a",
    kind: "temperature",
    status: "alive",
    entity_id: "ent_temp_a",
    source: "local gateway",
    sync_status: "synced",
    last_sync: "2026-05-19 09:01",
    registry_status: "linked",
    last_reading: { value: "22.7 °C", observed_at: "2026-05-19 09:00:55" },
    conclusions: ["temperatura estável; sem ação"],
  },
  {
    id: "s_humid_a",
    name: "humid_sensor_a",
    kind: "humidity",
    status: "alive",
    source: "local gateway",
    sync_status: "synced",
    last_sync: "2026-05-19 09:01",
    registry_status: "candidate",
    last_reading: { value: "48 %", observed_at: "2026-05-19 09:00:55" },
    conclusions: ["umidade dentro da janela esperada"],
  },
  {
    id: "s_door",
    name: "door_contact_main",
    kind: "contact",
    status: "unregistered",
    entity_id: "ent_door",
    source: "local gateway",
    sync_status: "pending_registry",
    last_sync: "2026-05-19 08:42",
    registry_status: "candidate",
    last_reading: { value: "open", observed_at: "2026-05-19 08:42:11" },
    conclusions: ["sinal de acesso apareceu antes de fechar Registry"],
  },
  {
    id: "s_presence_a",
    name: "presence_sensor_a",
    kind: "presence",
    status: "silent",
    source: "local gateway",
    sync_status: "stale",
    last_sync: "2026-05-19 05:12",
    registry_status: "missing",
    last_reading: { value: "no movement", observed_at: "2026-05-19 05:12:02" },
    conclusions: ["sala ficou sem atividade por 4h; validar se esperado"],
  },
];

export const STUB_LAB_REPORT = `## Hello Daniel

**Today is May 19th.**

This this and that happened. You have to see this.

### This cannot wait

- LAB 256 está com conectividade intermitente desde 08:58.
- door_contact_main apareceu como sinal, mas ainda não fechou Registry.
- A rotina matinal humana não foi confirmada; está como ghost.

### What closed

| Area | Result | Evidence |
|---|---|---|
| Backup | fechado | receipt r_101 |
| Registry | temp_sensor_a registrado | receipt r_102 |
| Machines | LAB 512 heartbeat confirmado | receipt r_104 |

### Suggested actions

- Abrir Machines e inspecionar LAB 256.
- Converter door_contact_main em entidade do Registry.
- Resolver ghost da rotina matinal com evidência ou manter como ghost.
`;

export const STUB_SENSOR_CONCLUSIONS = [
  "A sala ficou sem atividade por 4h; validar se esperado.",
  "LAB 512 está vivo e útil; operador local respondeu health check.",
  "Há 1 sinal não cadastrado que deve virar Registry ou Ghost.",
  "Última sync Supabase foi há 2 min; sem falha crítica.",
];

/* ─── Wave 3: workorders / schedules / appointments / agents / routines ── */
/* All entries are stub/demo and not persisted. */

export const STUB_AGENTS: Agent[] = [
  {
    id: "agent_local_op",
    name: "Local Registry Operator",
    role: "registry translator",
    status: "present",
    last_check_in: "2026-05-19 09:01",
    llm_id: "llm_local_operator",
    runtime_id: "rt_ollama_lab512",
    assigned_workflows: ["sch_research_review", "sch_morning_routine"],
    permissions: ["observe", "propose", "register"],
    recent_runs: [
      {
        id: "ar_local_001",
        when: "2026-05-19 09:01",
        what: "classify · proposta cadastrar door_contact_main",
        status: "ok",
        receipt_id: "r_102",
      },
      {
        id: "ar_local_002",
        when: "2026-05-19 08:55",
        what: "translate · 12 LogLines",
        status: "ok",
      },
      {
        id: "ar_local_003",
        when: "2026-05-19 08:11",
        what: "register · sensor temp_sensor_a",
        status: "ok",
        receipt_id: "r_102",
      },
    ],
  },
  {
    id: "agent_keeper",
    name: "LAB Keeper",
    role: "observability watcher",
    status: "present",
    last_check_in: "2026-05-19 09:00",
    runtime_id: "rt_minilab_agent_lab8gb",
    assigned_workflows: ["sch_heartbeat", "sch_backup"],
    permissions: ["observe", "propose"],
    recent_runs: [
      {
        id: "ar_keep_001",
        when: "2026-05-19 09:00",
        what: "machine heartbeat sweep",
        status: "ok",
        receipt_id: "r_104",
      },
      {
        id: "ar_keep_002",
        when: "2026-05-19 03:14",
        what: "supabase backup checked",
        status: "ok",
        receipt_id: "r_101",
      },
      {
        id: "ar_keep_003",
        when: "2026-05-19 08:58",
        what: "lab-256 heartbeat atrasou",
        status: "warn",
      },
    ],
  },
  {
    id: "agent_cleaner",
    name: "Cleaning Routine Agent",
    role: "physical routine reminder",
    status: "degraded",
    last_check_in: "2026-05-19 06:30",
    assigned_workflows: ["sch_cleaning"],
    permissions: ["observe", "remind"],
    recent_runs: [
      {
        id: "ar_clean_001",
        when: "2026-05-19 06:30",
        what: "lembrete da rotina matinal",
        status: "warn",
        ghost_id: "g_001",
      },
      {
        id: "ar_clean_002",
        when: "2026-05-15 09:00",
        what: "limpeza semanal · semana 20",
        status: "ok",
      },
    ],
    ghost_id: "g_001",
  },
  {
    id: "agent_supply",
    name: "Supply Watch",
    role: "supplies & vendors monitor",
    status: "scheduled",
    last_check_in: "2026-05-18 17:00",
    assigned_workflows: ["sch_hepa_supply", "sch_finance_review"],
    permissions: ["observe", "propose"],
    recent_runs: [
      {
        id: "ar_sup_001",
        when: "2026-05-18 17:08",
        what: "HEPA · faltou recibo do mês anterior",
        status: "bad",
        ghost_id: "g_002",
      },
    ],
  },
  {
    id: "agent_quiet_watcher",
    name: "Quiet Watcher",
    role: "after-hours observation",
    status: "absent",
    last_check_in: "2026-05-18 22:00",
    assigned_workflows: [],
    permissions: ["observe"],
    recent_runs: [],
    ghost_id: "g_003",
  },
];

export const STUB_HUMAN_CHECKINS: HumanCheckIn[] = [
  { id: "hc_dan_morning", who: "Daniel", when: "2026-05-19 07:50", status: "missing" },
  { id: "hc_dan_noon", who: "Daniel", when: "2026-05-19 12:30", status: "confirmed" },
];

export const STUB_WORKORDERS: Workorder[] = [
  {
    id: "wo_draft_001",
    title: "Cadastrar door_contact_main no Registry",
    intent: "register sensor signal as Registry entity",
    scope: "registry · sensor",
    state: "draft",
    created_at: "2026-05-19 08:43",
    required_evidence: ["sensor_id", "registry_role", "domain"],
    linked_entities: ["ent_door"],
    ghost_id: "g_004",
  },
  {
    id: "wo_cand_002",
    title: "Limpeza do Laboratório Santo Andre",
    intent: "physical cleaning routine",
    scope: "santo-andre · cleaning",
    state: "candidate",
    created_at: "2026-05-19 07:30",
    required_evidence: ["photo_before", "photo_after", "human_confirmation"],
    ghost_id: "g_001",
  },
  {
    id: "wo_wait_003",
    title: "Restart LAB 256 (router check)",
    intent: "investigar wifi intermitente",
    scope: "machines · maintenance",
    state: "waiting_approval",
    authority: "Daniel",
    created_at: "2026-05-19 08:59",
    required_evidence: ["pre_restart_log", "post_restart_log"],
    linked_entities: ["ent_lab256"],
    gate_decision: "needs_approval",
    gate_reason: "ação protegida; humano precisa confirmar.",
  },
  {
    id: "wo_run_004",
    title: "Benchmark inicial · Local Registry Operator",
    intent: "medir latência do operador local",
    scope: "llms · benchmark",
    state: "running",
    created_at: "2026-05-19 08:51",
    linked_entities: ["ent_local_operator", "ent_lab512"],
  },
  {
    id: "wo_block_005",
    title: "Compra de filtro HEPA",
    intent: "anexar recibo da compra anterior antes de nova ordem",
    scope: "vendors · supply",
    state: "blocked",
    created_at: "2026-05-18 17:08",
    blocked_reason: "recibo anterior não anexado; ghost g_002 aberto",
    ghost_id: "g_002",
  },
  {
    id: "wo_closed_006",
    title: "Backup noturno do Supabase",
    intent: "snapshot e digest da base online",
    scope: "infra · backup",
    state: "closed",
    created_at: "2026-05-19 03:00",
    receipt_id: "r_101",
  },
  {
    id: "wo_closed_007",
    title: "Build da official UI",
    intent: "produção de UI sem erro",
    scope: "code · build",
    state: "closed",
    created_at: "2026-05-19 08:55",
    receipt_id: "r_104",
  },
  {
    id: "wo_ghost_008",
    title: "Rotina matinal humana",
    intent: "registrar presença e energia",
    scope: "human · routine",
    state: "ghosted",
    created_at: "2026-05-19 07:00",
    ghost_id: "g_003",
  },
];

export const STUB_SCHEDULES: Schedule[] = [
  {
    id: "sch_backup",
    title: "Supabase backup",
    cadence: "daily",
    domain: "infra",
    next_run: "2026-05-20 03:00",
    last_run: "2026-05-19 03:14",
    status: "recurring",
    receipt_id: "r_101",
    quality: 1.0,
  },
  {
    id: "sch_morning_routine",
    title: "Rotina matinal humana",
    cadence: "daily",
    domain: "human",
    next_run: "2026-05-20 07:00",
    last_run: "2026-05-19 07:00",
    status: "missed",
    ghost_id: "g_003",
    quality: 0,
  },
  {
    id: "sch_cleaning",
    title: "Limpeza Santo Andre",
    cadence: "weekly",
    domain: "santo-andre",
    next_run: "2026-05-22 09:00",
    last_run: "2026-05-15 09:00",
    status: "upcoming",
    quality: 0.6,
  },
  {
    id: "sch_heartbeat",
    title: "Machines heartbeat sweep",
    cadence: "hourly",
    domain: "machines",
    next_run: "2026-05-19 10:00",
    last_run: "2026-05-19 09:00",
    status: "recurring",
    receipt_id: "r_104",
    quality: 0.95,
  },
  {
    id: "sch_hepa_supply",
    title: "Reposição de filtro HEPA",
    cadence: "monthly",
    domain: "vendors",
    next_run: "2026-06-01 10:00",
    last_run: "2026-04-30 10:00",
    status: "missed",
    ghost_id: "g_002",
    quality: 0.3,
  },
  {
    id: "sch_finance_review",
    title: "Conferência mensal de gastos",
    cadence: "monthly",
    domain: "financeiro",
    next_run: "2026-05-31 18:00",
    status: "upcoming",
    quality: 0.8,
  },
  {
    id: "sch_research_review",
    title: "Triagem de papers da semana",
    cadence: "weekly",
    domain: "research",
    next_run: "2026-05-23 16:00",
    last_run: "2026-05-16 16:00",
    status: "upcoming",
    quality: 0.7,
  },
  {
    id: "sch_ui_build_closed",
    title: "UI build smoke",
    cadence: "ad_hoc",
    domain: "code",
    last_run: "2026-05-19 08:55",
    status: "completed",
    receipt_id: "r_104",
    quality: 1.0,
  },
];

export const STUB_APPOINTMENTS: Appointment[] = [
  {
    id: "appt_morning_routine",
    when: "07:00",
    title: "Rotina matinal humana",
    domain: "human",
    state: "missed",
  },
  {
    id: "appt_heartbeat",
    when: "09:00",
    title: "Heartbeat sweep das máquinas",
    domain: "machines",
    state: "done",
    receipt_id: "r_104",
  },
  {
    id: "appt_now",
    when: "09:30",
    title: "Inspeção do report do LAB",
    domain: "lab",
    state: "now",
  },
  {
    id: "appt_register_door",
    when: "10:30",
    title: "Cadastrar door_contact_main",
    domain: "registry",
    state: "upcoming",
    workorder_id: "wo_draft_001",
  },
  {
    id: "appt_lab512_review",
    when: "14:00",
    title: "Inspecionar LAB 512 (idle / uso)",
    domain: "machines",
    state: "upcoming",
    workorder_id: "wo_run_004",
  },
  {
    id: "appt_cleaning",
    when: "16:00",
    title: "Limpeza Santo Andre · evidência",
    domain: "santo-andre",
    state: "upcoming",
    workorder_id: "wo_cand_002",
  },
];

export const STUB_ROUTINE_ENTRIES: RoutineEntry[] = [
  {
    id: "rt_research",
    group: "Research",
    title: "Triagem de papers da semana",
    expected: "ler 3 papers e registrar 1 hipótese",
    observed: "pendente · ainda no horário",
    status: "in_progress",
    quality_impact: 0,
  },
  {
    id: "rt_workflows",
    group: "Scheduled workflows",
    title: "Backup noturno Supabase",
    expected: "snapshot em 03:00 com digest",
    observed: "fechou em 8m22s · receipt r_101",
    status: "done",
    receipt_id: "r_101",
    quality_impact: 1,
  },
  {
    id: "rt_agents",
    group: "Agents",
    title: "LAB Keeper presente",
    expected: "check-in até 09:00",
    observed: "presente · check-in 09:00",
    status: "done",
    quality_impact: 1,
  },
  {
    id: "rt_agent_cleaner",
    group: "Agents",
    title: "Cleaning Routine Agent",
    expected: "lembrar rotina das 07:00",
    observed: "degradado · resposta atrasada",
    status: "missed",
    quality_impact: -1,
    ghost_id: "g_001",
  },
  {
    id: "rt_human",
    group: "Human",
    title: "Daniel · rotina matinal",
    expected: "confirmar presença e energia até 08:00",
    observed: "sem confirmação",
    status: "ghost",
    ghost_id: "g_003",
    quality_impact: -1,
  },
  {
    id: "rt_maintenance",
    group: "Maintenance",
    title: "Inspeção do roteador",
    expected: "checar sinal e reposicionar",
    observed: "ainda não realizada · LAB 256 intermitente",
    status: "in_progress",
    quality_impact: -1,
  },
  {
    id: "rt_cleaning",
    group: "Cleaning",
    title: "Limpeza Santo Andre",
    expected: "limpeza semanal com evidência",
    observed: "sem foto/confirmação",
    status: "ghost",
    ghost_id: "g_001",
    quality_impact: -1,
  },
  {
    id: "rt_finance",
    group: "Finance checks",
    title: "Conferência mensal de gastos",
    expected: "fechar mês com vendor matches",
    observed: "agendada para 31/05",
    status: "in_progress",
    quality_impact: 0,
  },
];

/* ─── Wave 4: gates / knowledge / docs / llms ─────────────────────────── */

export const STUB_GATE_DECISIONS: GateDecisionRecord[] = [
  {
    id: "gd_lab256_restart",
    scope: "workorder · restart lab-256",
    decision: "needs_approval",
    reason: "ação protegida; humano precisa confirmar.",
    policy_id: "policy.machines.restart",
    authority: "Daniel",
    evidence: ["pre_restart_log"],
    created_at: "2026-05-19 08:59",
    workorder_id: "wo_wait_003",
  },
  {
    id: "gd_supabase_backup",
    scope: "workorder · supabase backup nightly",
    decision: "ok",
    reason: "rotina conhecida e dentro da janela permitida.",
    policy_id: "policy.infra.backup",
    authority: "auto-routine",
    evidence: ["scheduled_window", "previous_receipt_chain"],
    created_at: "2026-05-19 03:00",
    workorder_id: "wo_closed_006",
  },
  {
    id: "gd_hepa_supply",
    scope: "workorder · hepa filter order",
    decision: "denied",
    reason: "recibo anterior não anexado; vendor sem prova fechada.",
    policy_id: "policy.vendors.recurring_purchase",
    authority: "Daniel",
    evidence: [],
    created_at: "2026-05-18 17:08",
    workorder_id: "wo_block_005",
  },
  {
    id: "gd_morning_routine",
    scope: "routine · human morning",
    decision: "ghost",
    reason: "humano não confirmou; rotina vira ghost honesto.",
    policy_id: "policy.human.routine_required",
    authority: "Daniel",
    evidence: [],
    created_at: "2026-05-19 08:00",
  },
  {
    id: "gd_ui_build",
    scope: "workorder · ui build",
    decision: "ok",
    reason: "build observado; sem regressão de validators.",
    policy_id: "policy.code.build",
    authority: "auto-routine",
    evidence: ["typecheck", "validate:ui"],
    created_at: "2026-05-19 08:55",
    workorder_id: "wo_closed_007",
  },
  {
    id: "gd_unknown_signal",
    scope: "registry · door_contact_main",
    decision: "needs_approval",
    reason: "sinal apareceu antes de Registry; precisa de role + domain.",
    policy_id: "policy.registry.no_direct_edit",
    authority: "Daniel",
    evidence: ["sensor_reading_at_08:42"],
    created_at: "2026-05-19 08:43",
    workorder_id: "wo_draft_001",
  },
  {
    id: "gd_runtime_update_error",
    scope: "workorder · lab-512 runtime update",
    decision: "error",
    reason: "checagem de hash falhou antes de aplicar; abortar sem alterar.",
    policy_id: "policy.runtimes.signed_update",
    authority: "auto-gate",
    evidence: ["hash_mismatch"],
    created_at: "2026-05-19 04:10",
  },
];

export const STUB_KNOWLEDGE: KnowledgeItem[] = [
  {
    id: "kn_lab_routine_pb",
    title: "Playbook · Rotina diária do LAB",
    kind: "playbook",
    summary:
      "Sequência de checagens humanas, agentes e workflows que compõem o dia operacional do LAB.",
    domain: "operations",
    pinned: true,
    tags: ["routine", "human", "agent"],
    used_by: ["agent_keeper", "agent_cleaner"],
    source: "internal",
    updated_at: "2026-05-19",
  },
  {
    id: "kn_supabase_backup_pb",
    title: "Playbook · Backup noturno do Supabase",
    kind: "playbook",
    summary:
      "Snapshot, validação de digest, sincronização com cofre off-site e fechamento de receipt.",
    domain: "infra",
    tags: ["backup", "supabase"],
    used_by: ["agent_keeper"],
    updated_at: "2026-05-15",
  },
  {
    id: "kn_lab_context",
    title: "Context · LAB Santo Andre",
    kind: "context_pack",
    summary:
      "Endereço físico, planta, máquinas, sensores instalados, contatos de manutenção e fornecedores recorrentes.",
    domain: "santo-andre",
    pinned: true,
    used_by: ["llm_local_operator", "agent_keeper"],
    updated_at: "2026-05-10",
  },
  {
    id: "kn_registry_canonical",
    title: "Context · LogLine canônico",
    kind: "context_pack",
    summary:
      "Forma canônica de 9 slots, regras de gate, regras de proposta vs execução, e como ghosts e receipts fecham o ciclo.",
    domain: "registry",
    pinned: true,
    tags: ["logline", "rules"],
    used_by: ["llm_local_operator"],
    updated_at: "2026-05-19",
  },
  {
    id: "kn_sensor_taxonomy",
    title: "Note · Taxonomia de sensores",
    kind: "note",
    summary:
      "Catálogo dos sensores instalados e suas convenções: kind, domain, registry role.",
    domain: "sensors",
    tags: ["taxonomy"],
    used_by: ["llm_local_operator"],
    updated_at: "2026-05-12",
  },
  {
    id: "kn_dan_preferences",
    title: "Pinned · Preferências do Daniel",
    kind: "pinned",
    summary:
      "Tom, idioma preferido, horários de foco, limites de premium e estilo de relatório.",
    domain: "human",
    pinned: true,
    used_by: ["agent_keeper", "llm_local_operator"],
    updated_at: "2026-05-18",
  },
];

export const STUB_DOCUMENTS: DocumentItem[] = [
  {
    id: "doc_runbook_backup",
    title: "Runbook · Recuperar Supabase de snapshot",
    kind: "runbook",
    status: "official",
    domain: "infra",
    pinned: true,
    updated_at: "2026-05-10",
    content:
      "## Recuperar Supabase\n\nQuando algo der errado com a base online, siga este runbook.\n\n### Pré-requisitos\n\n- Snapshot mais recente identificado pelo digest.\n- Acesso de admin restaurado.\n\n### Passos\n\n- Pausar workflows que escrevem.\n- Restaurar snapshot via console.\n- Validar digest contra registro online.\n- Religar workflows.\n\n### Encerramento\n\nFechar workorder com receipt; anexar digest restaurada.\n",
  },
  {
    id: "doc_lab_plan_2026",
    title: "Plano · LAB 2026",
    kind: "plan",
    status: "official",
    domain: "operations",
    pinned: true,
    updated_at: "2026-01-15",
  },
  {
    id: "doc_policy_no_premium",
    title: "Policy · Premium calls são escassos",
    kind: "policy",
    status: "official",
    domain: "llms",
    updated_at: "2026-04-22",
    content:
      "## Premium calls são escassos\n\nLLMs premium são recursos finitos.\n\n### Regras\n\n- Operador local é primeira tentativa.\n- Premium só quando proposta clara.\n- Receipt obrigatório por chamada premium.\n",
  },
  {
    id: "doc_legal_lease",
    title: "Contrato · Aluguel Santo Andre",
    kind: "legal",
    status: "official",
    domain: "legal",
    updated_at: "2026-03-01",
  },
  {
    id: "doc_report_2026_05",
    title: "Relatório · Maio 2026",
    kind: "report",
    status: "draft",
    domain: "operations",
    updated_at: "2026-05-19",
    content:
      "## Maio 2026\n\nObservações operacionais do mês.\n\n### Saúde do LAB\n\n- LAB 256 com wifi intermitente.\n- LAB 512 utilização baixa.\n\n### Decisões\n\nReceipt e ghost referenciados no ledger.\n",
  },
  {
    id: "doc_runbook_door",
    title: "Runbook · Cadastrar sensor de porta",
    kind: "runbook",
    status: "review",
    domain: "registry",
    updated_at: "2026-05-19",
  },
];

export const STUB_LLMS: LLMItem[] = [
  {
    id: "llm_local_operator",
    name: "Local Registry Operator",
    provider: "local · LAB 512",
    tier: "local",
    role: "operator",
    capabilities: ["registry_translate", "missing_field_detect", "ghost_propose"],
    cost_profile: "free · local inference",
    benchmark_status: "passing",
    usage_today: 124,
    limits: "throughput ~ 6 req/s",
    policy_ids: ["policy.registry.no_direct_edit"],
  },
  {
    id: "llm_local_translator",
    name: "Mini Translator",
    provider: "local · LAB 512",
    tier: "local",
    role: "translator",
    capabilities: ["pt_en", "summarize_short"],
    cost_profile: "free · local inference",
    benchmark_status: "passing",
    usage_today: 41,
  },
  {
    id: "llm_lab_keeper",
    name: "LAB Keeper Agent LLM",
    provider: "local · LAB 8GB",
    tier: "local",
    role: "agent",
    capabilities: ["observe", "report", "propose_workorder"],
    cost_profile: "free · local inference",
    benchmark_status: "passing",
    usage_today: 18,
  },
  {
    id: "llm_premium_judge",
    name: "Premium Judge",
    provider: "premium · external",
    tier: "premium",
    role: "judge",
    capabilities: ["evaluate", "rank", "cite"],
    cost_profile: "premium · escasso",
    benchmark_status: "scheduled",
    usage_today: 2,
    limits: "máx 10 chamadas/dia",
    policy_ids: ["policy.llms.premium_scarce"],
  },
  {
    id: "llm_premium_writer",
    name: "Premium Writer",
    provider: "premium · external",
    tier: "premium",
    role: "operator",
    capabilities: ["compose", "rewrite", "long_form"],
    cost_profile: "premium · escasso",
    benchmark_status: "regressed",
    usage_today: 5,
    limits: "máx 20 chamadas/dia",
    policy_ids: ["policy.llms.premium_scarce"],
  },
  {
    id: "llm_chatbot_lab",
    name: "LAB Companion Chatbot",
    provider: "local · LAB 256",
    tier: "local",
    role: "chatbot",
    capabilities: ["chat", "context_recall"],
    cost_profile: "free · local inference",
    benchmark_status: "unknown",
    usage_today: 3,
  },
  {
    id: "llm_transistor_logline",
    name: "LogLine Transistor",
    provider: "local · LAB 512",
    tier: "local",
    role: "transistor",
    capabilities: ["logline_compress", "logline_expand"],
    cost_profile: "free · local inference",
    benchmark_status: "passing",
    usage_today: 67,
  },
];

export const PREMIUM_BUDGET_TODAY = 30; // total premium calls allowed today

/* ─── Wave 5a: reviews / policies / connections / secrets ─────────────── */

export const STUB_REVIEWS: ReviewItem[] = [
  {
    id: "rv_code_ui_build",
    title: "Diff · minilab official UI (Wave 5a)",
    kind: "diff",
    status: "in_review",
    scope: "code · ui",
    reviewer: "Daniel",
    created_at: "2026-05-19 09:00",
    risks: ["touches preview switch", "adds 4 routes"],
    checks: [
      { label: "typecheck", passed: true },
      { label: "validate:ui", passed: true },
      { label: "manual smoke", passed: false },
    ],
    comments: 3,
    diff_summary: "+4 areas · +1 preview case · +19 components · 0 catalog drift",
  },
  {
    id: "rv_wo_door_register",
    title: "Workorder · Cadastrar door_contact_main",
    kind: "workorder",
    status: "blocked",
    scope: "registry · sensor",
    created_at: "2026-05-19 08:50",
    blocked_reason: "ghost g_004 ainda aberto; falta role + domain.",
    workorder_id: "wo_draft_001",
    ghost_id: "g_004",
  },
  {
    id: "rv_policy_no_direct_edit",
    title: "Policy · no_direct_registry_edit",
    kind: "policy",
    status: "ready_to_close",
    scope: "registry",
    created_at: "2026-05-19 07:30",
    checks: [
      { label: "regra escrita", passed: true },
      { label: "gate vinculado", passed: true },
      { label: "exemplo de aplicação", passed: true },
    ],
    receipt_id: "r_102",
  },
  {
    id: "rv_doc_runbook_door",
    title: "Doc · Runbook · Cadastrar sensor de porta",
    kind: "document",
    status: "queued",
    scope: "docs · registry",
    created_at: "2026-05-19 08:20",
    document_id: "doc_runbook_door",
  },
  {
    id: "rv_gate_lab256_restart",
    title: "Gate · restart LAB 256",
    kind: "gate",
    status: "in_review",
    scope: "machines",
    created_at: "2026-05-19 08:59",
    risks: ["interrupção breve do workbench"],
    gate_id: "gd_lab256_restart",
    workorder_id: "wo_wait_003",
  },
  {
    id: "rv_legal_lease",
    title: "Legal · Aluguel Santo Andre · revisão anual",
    kind: "legal",
    status: "queued",
    scope: "legal",
    created_at: "2026-05-18 16:00",
    document_id: "doc_legal_lease",
  },
  {
    id: "rv_code_supabase_backup",
    title: "Diff · supabase backup script",
    kind: "diff",
    status: "closed",
    scope: "code · infra",
    created_at: "2026-05-15 22:00",
    checks: [
      { label: "typecheck", passed: true },
      { label: "smoke", passed: true },
    ],
    receipt_id: "r_101",
    diff_summary: "+1 file · validações de digest fortalecidas",
  },
  {
    id: "rv_wo_hepa",
    title: "Workorder · compra HEPA",
    kind: "workorder",
    status: "blocked",
    scope: "vendors · supply",
    created_at: "2026-05-18 17:10",
    blocked_reason: "ghost g_002; recibo anterior não anexado.",
    workorder_id: "wo_block_005",
    ghost_id: "g_002",
  },
];

export const STUB_POLICIES: PolicyItem[] = [
  {
    id: "policy.registry.no_direct_edit",
    name: "no_direct_registry_edit",
    status: "active",
    scope: ["registry"],
    rule_summary:
      "Mutações no Registry passam por AIProposalCard + gate. UI nunca edita diretamente.",
    applies_to: ["Registry", "EntityPreview", "RegistryTable"],
    linked_gates: ["gd_unknown_signal"],
    last_decision: "2026-05-19 08:43 · needs_approval",
    updated_at: "2026-05-10",
  },
  {
    id: "policy.records.online_only",
    name: "no_local_validity",
    status: "active",
    scope: ["records"],
    rule_summary: "Registro válido só existe online em bytes, não em estado local.",
    applies_to: ["RegisterActions", "AIProposalCard", "LogLineRecordCard"],
    linked_gates: ["gd_supabase_backup"],
    last_decision: "2026-05-19 03:00 · ok",
    updated_at: "2026-05-02",
  },
  {
    id: "policy.secrets.no_values",
    name: "no_secret_values",
    status: "active",
    scope: ["secrets"],
    rule_summary: "Nunca renderizar valores de segredos; só referências/presença.",
    applies_to: ["Secrets", "ProviderStatus", "SecretReferenceRows"],
    linked_gates: [],
    last_decision: "—",
    updated_at: "2026-04-15",
  },
  {
    id: "policy.machines.restart",
    name: "machines.restart",
    status: "active",
    scope: ["machines"],
    rule_summary:
      "Restart de máquinas exige aprovação humana e log pré/pós comparável.",
    applies_to: ["Machines", "ProtectedActions"],
    linked_gates: ["gd_lab256_restart"],
    last_decision: "2026-05-19 08:59 · needs_approval",
    updated_at: "2026-04-22",
  },
  {
    id: "policy.llms.premium_scarce",
    name: "llms.premium_scarce",
    status: "active",
    scope: ["llms"],
    rule_summary:
      "Chamadas premium são escassas; passa por gate de orçamento diário.",
    applies_to: ["LLMs"],
    linked_gates: [],
    last_decision: "2026-05-19 04:30 · ok",
    updated_at: "2026-04-22",
  },
  {
    id: "policy.vendors.recurring_purchase",
    name: "vendors.recurring_purchase",
    status: "needs_review",
    scope: ["vendors"],
    rule_summary:
      "Compras recorrentes só podem ser autorizadas se recibo anterior estiver fechado.",
    applies_to: ["Vendors", "Workorders"],
    linked_gates: ["gd_hepa_supply"],
    last_decision: "2026-05-18 17:08 · denied",
    updated_at: "2026-05-12",
  },
  {
    id: "policy.runtimes.signed_update",
    name: "runtimes.signed_update",
    status: "active",
    scope: ["runtimes", "machines"],
    rule_summary:
      "Atualizações de runtime exigem checagem de hash antes de aplicar.",
    applies_to: ["Runtimes", "Machines"],
    linked_gates: ["gd_runtime_update_error"],
    last_decision: "2026-05-19 04:10 · error",
    updated_at: "2026-04-30",
  },
  {
    id: "policy.routines.required_human_confirmation",
    name: "human.routine_required",
    status: "draft",
    scope: ["human", "routines"],
    rule_summary:
      "Rotinas humanas precisam de confirmação humana; falta → ghost.",
    applies_to: ["LabRoutine", "Today"],
    linked_gates: ["gd_morning_routine"],
    last_decision: "2026-05-19 08:00 · ghost",
    updated_at: "2026-05-19",
  },
  {
    id: "policy.deprecated.print_anywhere",
    name: "deprecated.print_anywhere",
    status: "retired",
    scope: ["dev"],
    rule_summary:
      "Política antiga de log em stdout. Substituída por receipts online.",
    applies_to: [],
    linked_gates: [],
    updated_at: "2025-12-01",
  },
];

export const STUB_SECRETS: SecretReference[] = [
  {
    id: "sec_supabase_service",
    logical_name: "SUPABASE_SERVICE_KEY",
    provider: "Doppler",
    scope: "infra · supabase.prod",
    presence: "present",
    last_rotation: "2026-04-01",
    policy_ids: ["policy.secrets.no_values"],
    dependents: ["conn_supabase", "agent_keeper"],
  },
  {
    id: "sec_cloudflare_api",
    logical_name: "CLOUDFLARE_API_TOKEN",
    provider: "Doppler",
    scope: "infra · cloudflare",
    presence: "present",
    last_rotation: "2026-03-15",
    policy_ids: ["policy.secrets.no_values"],
    dependents: ["conn_cloudflare"],
  },
  {
    id: "sec_github_pat",
    logical_name: "GITHUB_PAT",
    provider: "Doppler",
    scope: "code · github",
    presence: "stale",
    last_rotation: "2025-11-02",
    policy_ids: ["policy.secrets.no_values"],
    dependents: ["conn_github"],
  },
  {
    id: "sec_premium_llm",
    logical_name: "PREMIUM_LLM_KEY",
    provider: "Doppler",
    scope: "llms · premium",
    presence: "missing",
    policy_ids: ["policy.secrets.no_values", "policy.llms.premium_scarce"],
    dependents: ["conn_premium_llm", "llm_premium_judge", "llm_premium_writer"],
  },
  {
    id: "sec_slack_webhook",
    logical_name: "SLACK_WEBHOOK_URL",
    provider: "env",
    scope: "communication · slack",
    presence: "present",
    last_rotation: "2026-02-10",
    policy_ids: ["policy.secrets.no_values"],
    dependents: ["conn_slack"],
  },
  {
    id: "sec_smtp_pass",
    logical_name: "SMTP_PASSWORD",
    provider: "env",
    scope: "communication · email",
    presence: "missing",
    policy_ids: ["policy.secrets.no_values"],
    dependents: ["conn_smtp"],
  },
  {
    id: "sec_finance_token",
    logical_name: "FINANCE_PROVIDER_TOKEN",
    provider: "Doppler",
    scope: "finance",
    presence: "present",
    last_rotation: "2026-05-10",
    policy_ids: ["policy.secrets.no_values"],
    dependents: ["conn_finance"],
  },
];

export const STUB_CONNECTIONS: ConnectionItem[] = [
  {
    id: "conn_supabase",
    name: "supabase.prod",
    provider: "Supabase",
    domain: "storage",
    state: "connected",
    last_sync: "2026-05-19 09:01",
    scope: "database · realtime · auth",
    secret_refs: ["sec_supabase_service"],
    policy_ids: ["policy.records.online_only"],
  },
  {
    id: "conn_cloudflare",
    name: "cloudflare",
    provider: "Cloudflare",
    domain: "runtime",
    state: "connected",
    last_sync: "2026-05-19 08:00",
    scope: "dns · workers · r2",
    secret_refs: ["sec_cloudflare_api"],
  },
  {
    id: "conn_github",
    name: "github",
    provider: "GitHub",
    domain: "code",
    state: "degraded",
    last_sync: "2026-05-19 07:00",
    scope: "repos · actions",
    secret_refs: ["sec_github_pat"],
    risks: ["PAT estala em ~10 dias"],
  },
  {
    id: "conn_premium_llm",
    name: "premium llm provider",
    provider: "external",
    domain: "runtime",
    state: "missing",
    scope: "premium chat completion",
    secret_refs: ["sec_premium_llm"],
    policy_ids: ["policy.llms.premium_scarce"],
    risks: ["chave ausente; chamadas premium não rodam"],
  },
  {
    id: "conn_slack",
    name: "slack",
    provider: "Slack",
    domain: "communication",
    state: "connected",
    last_sync: "2026-05-19 09:00",
    scope: "alerts · receipts",
    secret_refs: ["sec_slack_webhook"],
  },
  {
    id: "conn_smtp",
    name: "smtp",
    provider: "self-hosted",
    domain: "communication",
    state: "missing",
    scope: "email out",
    secret_refs: ["sec_smtp_pass"],
    risks: ["senha SMTP ausente"],
  },
  {
    id: "conn_doppler",
    name: "doppler",
    provider: "Doppler",
    domain: "runtime",
    state: "connected",
    last_sync: "2026-05-19 08:55",
    scope: "secret vault",
  },
  {
    id: "conn_finance",
    name: "finance provider",
    provider: "external",
    domain: "finance",
    state: "connected",
    last_sync: "2026-05-18 18:00",
    scope: "billing · vendor sync",
    secret_refs: ["sec_finance_token"],
  },
  {
    id: "conn_legal_drive",
    name: "legal drive",
    provider: "external",
    domain: "legal",
    state: "degraded",
    last_sync: "2026-05-17 10:00",
    scope: "contract storage",
    risks: ["última sync há 2 dias"],
  },
  {
    id: "conn_mcp_registry",
    name: "MCP registry",
    provider: "anthropic",
    domain: "runtime",
    state: "configuring",
    scope: "tools marketplace",
  },
];

/* ─── Wave 5b: financeiro / costs / vendors / legal ───────────────────── */

export const STUB_ADDRESSES: AddressItem[] = [
  {
    id: "addr_commercial",
    label: "Endereço comercial oficial",
    purpose: "commercial",
    lines: ["Rua Misericórdia 14, Loja 5", "1200-273 Lisboa"],
    country: "Portugal",
  },
  {
    id: "addr_lab",
    label: "Endereço físico do LAB",
    purpose: "physical_lab",
    lines: ["Calçada de Santo André 70, 1 Esquerdo", "Lisboa"],
    country: "Portugal",
  },
];

export const STUB_VENDORS: VendorItem[] = [
  {
    id: "vendor_supabase",
    name: "Supabase",
    kind: "saas",
    state: "recurring",
    service: "managed Postgres + auth + storage",
    contact: { name: "Vendor support", email: "support@supabase.com", site: "supabase.com" },
    contract_ids: ["legal_supabase_tos"],
    document_ids: ["doc_policy_no_premium"],
    receipt_ids: ["r_101"],
    monthly_cost_eur: 25,
    last_payment_at: "2026-05-01",
    payment_status: "ok",
  },
  {
    id: "vendor_cloudflare",
    name: "Cloudflare",
    kind: "infra",
    state: "recurring",
    service: "dns · workers · r2",
    contact: { site: "cloudflare.com" },
    monthly_cost_eur: 20,
    last_payment_at: "2026-05-03",
    payment_status: "ok",
  },
  {
    id: "vendor_doppler",
    name: "Doppler",
    kind: "saas",
    state: "recurring",
    service: "secret vault",
    contact: { site: "doppler.com" },
    monthly_cost_eur: 7,
    last_payment_at: "2026-05-02",
    payment_status: "ok",
  },
  {
    id: "vendor_github",
    name: "GitHub",
    kind: "saas",
    state: "active",
    service: "repos · actions",
    contact: { site: "github.com" },
    monthly_cost_eur: 4,
    last_payment_at: "2026-05-05",
    payment_status: "ok",
  },
  {
    id: "vendor_premium_llm",
    name: "Premium LLM provider",
    kind: "saas",
    state: "payment_issue",
    service: "premium chat completion",
    contact: { site: "external" },
    monthly_cost_eur: 80,
    payment_status: "blocked",
    ghost_ids: ["g_002"],
  },
  {
    id: "vendor_hepa",
    name: "HEPA filter supply",
    kind: "supply",
    state: "pending",
    service: "filtros HEPA recorrentes",
    contact: { phone: "+351 21 000 0000" },
    monthly_cost_eur: 35,
    last_payment_at: "2026-04-30",
    payment_status: "missing_invoice",
    ghost_ids: ["g_002"],
    receipt_ids: [],
  },
  {
    id: "vendor_landlord",
    name: "Senhorio Santo Andre",
    kind: "legal",
    state: "legal_attention",
    service: "arrendamento físico",
    contact: { phone: "+351 91 111 1111" },
    contract_ids: ["legal_lease"],
    document_ids: ["doc_legal_lease"],
    monthly_cost_eur: 950,
    last_payment_at: "2026-05-01",
    payment_status: "ok",
  },
  {
    id: "vendor_legal_office",
    name: "Escritório jurídico",
    kind: "professional_service",
    state: "active",
    service: "consultoria legal",
    contact: { email: "legal@escritorio.pt" },
    contract_ids: ["legal_advisor_retainer"],
    monthly_cost_eur: 150,
    last_payment_at: "2026-05-04",
    payment_status: "ok",
  },
  {
    id: "vendor_accountant",
    name: "Contabilidade Lisboa",
    kind: "professional_service",
    state: "active",
    service: "contabilidade mensal",
    contact: { email: "contas@example.pt" },
    monthly_cost_eur: 120,
    last_payment_at: "2026-05-01",
    payment_status: "ok",
  },
  {
    id: "vendor_electric",
    name: "Companhia de Energia",
    kind: "infra",
    state: "active",
    service: "eletricidade LAB",
    monthly_cost_eur: 90,
    last_payment_at: "2026-05-10",
    payment_status: "late",
  },
];

export const STUB_LEGAL: LegalRecord[] = [
  {
    id: "legal_lease",
    title: "Contrato de arrendamento · Calçada de Santo André 70",
    kind: "lease",
    status: "in_force",
    vendor_id: "vendor_landlord",
    document_id: "doc_legal_lease",
    risk: "medium",
    start_at: "2025-03-01",
    end_at: "2027-02-28",
    next_obligation: "2026-06-01 · próxima renda mensal",
    evidence: ["doc_legal_lease", "r_101"],
    receipt_id: "r_103",
  },
  {
    id: "legal_supabase_tos",
    title: "ToS · Supabase",
    kind: "contract",
    status: "in_force",
    vendor_id: "vendor_supabase",
    risk: "low",
    next_obligation: "—",
    evidence: ["doc_policy_no_premium"],
  },
  {
    id: "legal_advisor_retainer",
    title: "Retainer · Escritório jurídico",
    kind: "contract",
    status: "in_force",
    vendor_id: "vendor_legal_office",
    risk: "low",
    start_at: "2026-01-01",
    end_at: "2026-12-31",
    next_obligation: "2026-06-30 · revisão semestral",
  },
  {
    id: "legal_gdpr_compliance",
    title: "Compliance GDPR · Registo de tratamentos",
    kind: "compliance",
    status: "expiring",
    risk: "high",
    next_obligation: "2026-06-15 · revisar registos",
    evidence: [],
    ghost_id: "g_002",
  },
  {
    id: "legal_open_source_license",
    title: "Open-source license review",
    kind: "license",
    status: "draft",
    risk: "low",
    next_obligation: "—",
  },
  {
    id: "legal_tax_q2",
    title: "Obrigação fiscal · IVA Q2",
    kind: "obligation",
    status: "in_force",
    risk: "critical",
    next_obligation: "2026-07-20 · declarar e pagar IVA Q2",
  },
];

export const STUB_CORRESPONDENCE: CorrespondenceItem[] = [
  {
    id: "corr_landlord_apr",
    when: "2026-04-15",
    party: "Senhorio Santo Andre",
    subject: "Confirmação de recebimento · renda abril",
    channel: "email",
    summary: "Recibo de abril enviado; sem pendências.",
    legal_id: "legal_lease",
  },
  {
    id: "corr_at_iva",
    when: "2026-05-02",
    party: "AT · Portugal",
    subject: "Lembrete · IVA Q2 vence em 2026-07-20",
    channel: "letter",
    summary: "Aviso oficial de prazo.",
    legal_id: "legal_tax_q2",
  },
  {
    id: "corr_advisor",
    when: "2026-05-12",
    party: "Escritório jurídico",
    subject: "Próximos pontos GDPR",
    channel: "email",
    summary:
      "Pediram que enviemos o registo de tratamentos atualizado até 2026-06-15.",
    legal_id: "legal_gdpr_compliance",
  },
  {
    id: "corr_hepa_vendor",
    when: "2026-05-08",
    party: "HEPA filter supply",
    subject: "Recibo anterior pendente",
    channel: "email",
    summary:
      "Vendor cobrou novo pedido; respondemos que falta fechar o recibo anterior.",
  },
];

export const STUB_FINANCE_RECORDS: FinanceRecord[] = [
  {
    id: "fin_lease_may",
    title: "Renda Santo Andre · maio",
    vendor_id: "vendor_landlord",
    amount: 950,
    currency: "EUR",
    paid_at: "2026-05-01",
    category: "legal",
    status: "paid",
    document_id: "doc_legal_lease",
    receipt_id: "r_103",
    recurring: true,
  },
  {
    id: "fin_lease_june",
    title: "Renda Santo Andre · junho",
    vendor_id: "vendor_landlord",
    amount: 950,
    currency: "EUR",
    due_date: "2026-06-01",
    category: "legal",
    status: "scheduled",
    recurring: true,
  },
  {
    id: "fin_supabase_may",
    title: "Supabase Pro · maio",
    vendor_id: "vendor_supabase",
    amount: 25,
    currency: "EUR",
    paid_at: "2026-05-01",
    category: "infra",
    status: "paid",
    receipt_id: "r_101",
    recurring: true,
  },
  {
    id: "fin_cloudflare_may",
    title: "Cloudflare · maio",
    vendor_id: "vendor_cloudflare",
    amount: 20,
    currency: "EUR",
    paid_at: "2026-05-03",
    category: "infra",
    status: "paid",
    recurring: true,
  },
  {
    id: "fin_doppler_may",
    title: "Doppler · maio",
    vendor_id: "vendor_doppler",
    amount: 7,
    currency: "EUR",
    paid_at: "2026-05-02",
    category: "subscriptions",
    status: "paid",
    recurring: true,
  },
  {
    id: "fin_electric_may",
    title: "Eletricidade LAB · maio",
    vendor_id: "vendor_electric",
    amount: 90,
    currency: "EUR",
    due_date: "2026-05-20",
    category: "infra",
    status: "due",
    recurring: true,
  },
  {
    id: "fin_hepa_april",
    title: "HEPA filter supply · abril",
    vendor_id: "vendor_hepa",
    amount: 35,
    currency: "EUR",
    due_date: "2026-05-25",
    category: "supplies",
    status: "missing_evidence",
    ghost_id: "g_002",
    recurring: true,
  },
  {
    id: "fin_premium_llm_may",
    title: "Premium LLM provider · maio",
    vendor_id: "vendor_premium_llm",
    amount: 80,
    currency: "EUR",
    due_date: "2026-05-31",
    category: "subscriptions",
    status: "denied",
    gate_id: "gd_hepa_supply",
  },
  {
    id: "fin_legal_office_may",
    title: "Escritório jurídico · maio",
    vendor_id: "vendor_legal_office",
    amount: 150,
    currency: "EUR",
    paid_at: "2026-05-04",
    category: "legal",
    status: "paid",
    recurring: true,
  },
  {
    id: "fin_accountant_may",
    title: "Contabilidade · maio",
    vendor_id: "vendor_accountant",
    amount: 120,
    currency: "EUR",
    paid_at: "2026-05-01",
    category: "legal",
    status: "paid",
    recurring: true,
  },
  {
    id: "fin_iva_q2",
    title: "IVA Q2 (estimado)",
    amount: 420,
    currency: "EUR",
    due_date: "2026-07-20",
    category: "legal",
    status: "needs_approval",
    gate_id: "gd_supabase_backup",
  },
  {
    id: "fin_gpu_supply",
    title: "Upgrade SSD LAB 512",
    amount: 220,
    currency: "EUR",
    due_date: "2026-05-28",
    category: "supplies",
    status: "needs_approval",
  },
];

export const STUB_BUDGET: BudgetCategory[] = [
  { category: "infra", label: "Infra", budget: 200, spent: 135 },
  { category: "subscriptions", label: "Subscriptions", budget: 200, spent: 87 },
  { category: "supplies", label: "Supplies", budget: 100, spent: 35 },
  { category: "legal", label: "Legal & Tax", budget: 1300, spent: 1220 },
  { category: "people", label: "People", budget: 0, spent: 0 },
  { category: "research", label: "Research", budget: 150, spent: 0 },
  { category: "other", label: "Other", budget: 100, spent: 12 },
];

export const STUB_SPENDING_EVENTS: SpendingEvent[] = [
  {
    id: "spe_lease",
    when: "2026-05-01",
    title: "Renda Santo Andre",
    amount: 950,
    currency: "EUR",
    category: "legal",
    vendor_id: "vendor_landlord",
    receipt_id: "r_103",
  },
  {
    id: "spe_supabase",
    when: "2026-05-01",
    title: "Supabase Pro",
    amount: 25,
    currency: "EUR",
    category: "infra",
    vendor_id: "vendor_supabase",
    receipt_id: "r_101",
  },
  {
    id: "spe_cloudflare",
    when: "2026-05-03",
    title: "Cloudflare",
    amount: 20,
    currency: "EUR",
    category: "infra",
    vendor_id: "vendor_cloudflare",
  },
  {
    id: "spe_doppler",
    when: "2026-05-02",
    title: "Doppler",
    amount: 7,
    currency: "EUR",
    category: "subscriptions",
    vendor_id: "vendor_doppler",
  },
  {
    id: "spe_legal_office",
    when: "2026-05-04",
    title: "Escritório jurídico",
    amount: 150,
    currency: "EUR",
    category: "legal",
    vendor_id: "vendor_legal_office",
  },
  {
    id: "spe_accountant",
    when: "2026-05-01",
    title: "Contabilidade",
    amount: 120,
    currency: "EUR",
    category: "legal",
    vendor_id: "vendor_accountant",
  },
  {
    id: "spe_github",
    when: "2026-05-05",
    title: "GitHub",
    amount: 4,
    currency: "EUR",
    category: "subscriptions",
    vendor_id: "vendor_github",
  },
  {
    id: "spe_hepa_april",
    when: "2026-04-30",
    title: "HEPA filter (sem comprovante)",
    amount: 35,
    currency: "EUR",
    category: "supplies",
    vendor_id: "vendor_hepa",
    ghost_id: "g_002",
  },
];

export const STUB_COSTS: CostRecord[] = [
  {
    id: "cost_lab_256",
    cost_object_kind: "machine",
    cost_object_id: "ent_lab256",
    cost_object_label: "LAB 256",
    amount_eur: 38,
    period: "2026-05",
    source: "energia + maintenance estimada",
  },
  {
    id: "cost_lab_512",
    cost_object_kind: "machine",
    cost_object_id: "ent_lab512",
    cost_object_label: "LAB 512",
    amount_eur: 46,
    period: "2026-05",
    source: "energia + workload estimada",
    anomaly: true,
    delta_from_avg_pct: 65,
  },
  {
    id: "cost_lab_8gb",
    cost_object_kind: "machine",
    cost_object_id: "ent_lab8gb",
    cost_object_label: "LAB 8GB",
    amount_eur: 12,
    period: "2026-05",
    source: "energia leve",
  },
  {
    id: "cost_llm_local_op",
    cost_object_kind: "llm",
    cost_object_id: "llm_local_operator",
    cost_object_label: "Local Registry Operator",
    amount_eur: 0,
    period: "2026-05",
    source: "local · sem custo direto",
  },
  {
    id: "cost_llm_premium_judge",
    cost_object_kind: "llm",
    cost_object_id: "llm_premium_judge",
    cost_object_label: "Premium Judge",
    amount_eur: 18,
    period: "2026-05",
    source: "premium meter · 2 chamadas hoje",
    anomaly: false,
    receipt_id: "r_102",
  },
  {
    id: "cost_llm_premium_writer",
    cost_object_kind: "llm",
    cost_object_id: "llm_premium_writer",
    cost_object_label: "Premium Writer",
    amount_eur: 47,
    period: "2026-05",
    source: "premium meter · 5 chamadas hoje",
    anomaly: true,
    delta_from_avg_pct: 120,
  },
  {
    id: "cost_vendor_supabase",
    cost_object_kind: "vendor",
    cost_object_id: "vendor_supabase",
    cost_object_label: "Supabase",
    amount_eur: 25,
    period: "2026-05",
    source: "fatura · maio",
    receipt_id: "r_101",
  },
  {
    id: "cost_vendor_hepa",
    cost_object_kind: "vendor",
    cost_object_id: "vendor_hepa",
    cost_object_label: "HEPA filter supply",
    amount_eur: 35,
    period: "2026-04",
    source: "compra sem comprovante",
    ghost_id: "g_002",
    anomaly: true,
    delta_from_avg_pct: 0,
  },
  {
    id: "cost_project_minilab_ui",
    cost_object_kind: "project",
    cost_object_id: "proj_minilab_ui",
    cost_object_label: "Project · minilab UI",
    amount_eur: 65,
    period: "2026-05",
    source: "soma das máquinas + premium calls do dia",
  },
  {
    id: "cost_workflow_backup",
    cost_object_kind: "workflow",
    cost_object_id: "sch_backup",
    cost_object_label: "Workflow · supabase backup",
    amount_eur: 0.4,
    period: "2026-05",
    source: "supabase egress estimado",
  },
  {
    id: "cost_benchmark_local_op",
    cost_object_kind: "benchmark",
    cost_object_id: "bm_local_op",
    cost_object_label: "Benchmark · Local Registry Operator",
    amount_eur: 0,
    period: "2026-05",
    source: "local · 0 custo",
  },
];

export const STUB_MCP_MARKETPLACE = [
  {
    id: "mcp_filesystem",
    name: "Filesystem",
    description: "Acesso a arquivos locais com escopo definido.",
    state: "available",
  },
  {
    id: "mcp_supabase",
    name: "Supabase",
    description: "Toolset oficial pra falar com Supabase.",
    state: "installed",
  },
  {
    id: "mcp_github",
    name: "GitHub",
    description: "Issues, PRs e repos via GitHub.",
    state: "installed",
  },
  {
    id: "mcp_slack",
    name: "Slack",
    description: "Postar e ler mensagens em canais.",
    state: "available",
  },
  {
    id: "mcp_observability",
    name: "Observability (logs / metrics)",
    description: "Métricas operacionais do LAB.",
    state: "available",
  },
] as const;

/* ─── Wave 6a: human / santo-andre / runtimes ─────────────────────────── */

export const STUB_CARE_ITEMS: CareItem[] = [
  {
    id: "care_water_morning",
    group: "hydration",
    title: "Beber água ao acordar",
    expected: "1 copo ao acordar",
    observed: "feito 07:42",
    status: "ok",
    last_at: "2026-05-19 07:42",
  },
  {
    id: "care_water_noon",
    group: "hydration",
    title: "Água até o meio-dia",
    expected: "1 litro acumulado",
    observed: "~ 0,4 L até 09:30",
    status: "due",
  },
  {
    id: "care_meal_breakfast",
    group: "food",
    title: "Café da manhã",
    expected: "1 refeição leve antes das 10:00",
    observed: "ainda não confirmado",
    status: "missing",
    ghost_id: "g_003",
  },
  {
    id: "care_meal_lunch",
    group: "food",
    title: "Almoço",
    expected: "refeição quente até 14:00",
    observed: "agendado 12:30",
    status: "due",
  },
  {
    id: "care_hygiene_shower",
    group: "hygiene",
    title: "Banho",
    expected: "diário · matinal",
    observed: "feito 06:55",
    status: "ok",
    last_at: "2026-05-19 06:55",
  },
  {
    id: "care_hygiene_teeth",
    group: "hygiene",
    title: "Higiene bucal",
    expected: "2x ao dia",
    observed: "manhã feito",
    status: "ok",
  },
  {
    id: "care_mental_quiet",
    group: "mental",
    title: "Silêncio de manhã",
    expected: "15 min sem tela antes do trabalho",
    observed: "pulado",
    status: "missing",
  },
  {
    id: "care_mental_walk",
    group: "mental",
    title: "Caminhada curta",
    expected: "20 min entre tarefas",
    status: "due",
  },
  {
    id: "care_social_message",
    group: "social",
    title: "Mensagem a alguém querido",
    expected: "1 contato real por dia",
    observed: "—",
    status: "due",
  },
  {
    id: "care_social_no_isolation",
    group: "social",
    title: "Sem isolamento prolongado",
    expected: "máx 8h sozinho sem contato",
    observed: "última interação 21h atrás",
    status: "missing",
  },
  {
    id: "care_peace_quiet_window",
    group: "peace",
    title: "Janela calma antes de dormir",
    expected: "30 min sem tela",
    observed: "ontem ok",
    status: "ok",
  },
  {
    id: "care_peace_no_alarms",
    group: "peace",
    title: "Sem alarmes desnecessários",
    expected: "minimizar pings",
    observed: "1 alerta gentil hoje",
    status: "ok",
  },
];

export const STUB_GENTLE_ALERTS: GentleAlertItem[] = [
  {
    id: "alert_food_morning",
    tone: "soft_warn",
    message: "Café da manhã ainda não foi confirmado.",
    suggestion: "Quando comer, anote como check-in. Não é urgência, é lembrete.",
  },
  {
    id: "alert_social",
    tone: "info",
    message: "Faz algumas horas sem interação social registrada.",
    suggestion: "Talvez mandar uma mensagem curta antes do próximo bloco.",
  },
  {
    id: "alert_hydration",
    tone: "info",
    message: "Hidratação está abaixo do habitual para esta hora.",
  },
];

export const STUB_SUPPLY_NEEDS: SupplyNeed[] = [
  { id: "sn_water", what: "Garrafas de água", category: "hydration", status: "low" },
  { id: "sn_fruit", what: "Fruta da semana", category: "food", needed_by: "2026-05-21", status: "low" },
  { id: "sn_soap", what: "Sabonete líquido", category: "hygiene", status: "stocked" },
  { id: "sn_lunch", what: "Refeição pronta hoje", category: "food", needed_by: "hoje", status: "missing" },
];

export const STUB_PHYSICAL_ASSETS: PhysicalAsset[] = [
  {
    id: "asset_workbench",
    name: "Mesa de trabalho principal",
    kind: "furniture",
    location: "LAB · sala 1",
    state: "ok",
    responsible: "Daniel",
    last_check: "2026-05-15",
  },
  {
    id: "asset_router",
    name: "Roteador wifi LAB",
    kind: "infrastructure",
    location: "LAB · entrada",
    state: "needs_maintenance",
    responsible: "Daniel",
    last_check: "2026-05-19",
    workorder_id: "wo_wait_003",
  },
  {
    id: "asset_hepa",
    name: "Purificador HEPA",
    kind: "equipment",
    location: "LAB · sala 1",
    state: "needs_maintenance",
    responsible: "Daniel",
    last_check: "2026-04-30",
    ghost_id: "g_002",
  },
  {
    id: "asset_lab_256",
    name: "Mac mini · LAB 256",
    kind: "machine",
    location: "LAB · sala 1",
    state: "needs_maintenance",
    responsible: "Daniel",
    last_check: "2026-05-19",
    workorder_id: "wo_wait_003",
  },
  {
    id: "asset_lab_512",
    name: "Mac mini · LAB 512",
    kind: "machine",
    location: "LAB · sala 1",
    state: "ok",
    responsible: "Daniel",
    last_check: "2026-05-19",
  },
  {
    id: "asset_lab_8gb",
    name: "Mac mini · LAB 8GB",
    kind: "machine",
    location: "LAB · sala 1",
    state: "ok",
    responsible: "Daniel",
    last_check: "2026-05-19",
  },
  {
    id: "asset_chair",
    name: "Cadeira de trabalho",
    kind: "furniture",
    location: "LAB · sala 1",
    state: "ok",
    responsible: "Daniel",
    last_check: "2026-05-01",
  },
  {
    id: "asset_extinguisher",
    name: "Extintor de incêndio",
    kind: "equipment",
    location: "LAB · entrada",
    state: "ok",
    last_check: "2026-03-10",
  },
];

export const STUB_MAINTENANCE_TASKS: MaintenanceTask[] = [
  {
    id: "mt_router_check",
    title: "Inspecionar roteador (sinal intermitente)",
    asset_id: "asset_router",
    due_at: "2026-05-19",
    status: "in_progress",
    workorder_id: "wo_wait_003",
  },
  {
    id: "mt_hepa_filter",
    title: "Trocar filtro HEPA",
    asset_id: "asset_hepa",
    due_at: "2026-05-25",
    status: "scheduled",
    workorder_id: "wo_block_005",
    ghost_id: "g_002",
  },
  {
    id: "mt_lab256_reposition",
    title: "Reposicionar LAB 256 perto do roteador",
    asset_id: "asset_lab_256",
    due_at: "2026-05-19",
    status: "scheduled",
  },
  {
    id: "mt_extinguisher_review",
    title: "Validação anual do extintor",
    asset_id: "asset_extinguisher",
    due_at: "2026-09-10",
    status: "scheduled",
  },
  {
    id: "mt_workbench_polish",
    title: "Polimento mesa principal",
    asset_id: "asset_workbench",
    status: "done",
    receipt_id: "r_103",
  },
];

export const STUB_CLEANING: CleaningEntry[] = [
  {
    id: "cl_floor_weekly",
    area: "Chão · sala 1",
    cadence: "weekly",
    last_done: "2026-05-15",
    next_due: "2026-05-22",
    status: "due",
    ghost_id: "g_001",
  },
  {
    id: "cl_desk_daily",
    area: "Mesa principal",
    cadence: "daily",
    last_done: "2026-05-19",
    next_due: "2026-05-20",
    status: "done",
  },
  {
    id: "cl_machine_dust",
    area: "Pó nos Mac minis",
    cadence: "monthly",
    last_done: "2026-04-30",
    next_due: "2026-05-30",
    status: "done",
  },
  {
    id: "cl_kitchen",
    area: "Copa pequena",
    cadence: "weekly",
    last_done: "2026-05-13",
    next_due: "2026-05-20",
    status: "missed",
    ghost_id: "g_001",
  },
];

export const STUB_SUPPLY_LIST: SupplyEntry[] = [
  { id: "sl_hepa_filter", name: "Filtro HEPA reposição", category: "filter", state: "low", vendor_id: "vendor_hepa" },
  { id: "sl_screen_cloth", name: "Pano microfibra", category: "tool", state: "stocked" },
  { id: "sl_paper_towel", name: "Papel toalha", category: "consumable", state: "low" },
  { id: "sl_ethanol", name: "Álcool 70%", category: "consumable", state: "stocked" },
  { id: "sl_label_printer", name: "Etiqueta para impressora", category: "consumable", state: "missing" },
];

export const STUB_SPACE_OBSERVATIONS: SpaceObservation[] = [
  {
    id: "so_router_pos",
    when: "2026-05-19 08:58",
    area: "entrada",
    message: "Roteador está atrás do gabinete; sinal pode estar fraco no fundo da sala 1.",
    tone: "warn",
  },
  {
    id: "so_floor_dust",
    when: "2026-05-19 07:30",
    area: "sala 1",
    message: "Pó visível perto da janela; limpeza semanal atrasou.",
    tone: "warn",
  },
  {
    id: "so_temperature",
    when: "2026-05-19 09:00",
    area: "sala 1",
    message: "Temperatura confortável (22,7 °C) e umidade estável.",
    tone: "info",
  },
  {
    id: "so_door_signal",
    when: "2026-05-19 08:42",
    area: "porta principal",
    message: "Sinal de contato apareceu sem que o Registry tivesse a entidade.",
    tone: "warn",
  },
];

export const STUB_ENFORCEMENT: EnforcementRule[] = [
  {
    id: "en_no_food_lab",
    rule: "Sem comida em cima da mesa dos Mac minis.",
    status: "active",
  },
  {
    id: "en_weekly_clean",
    rule: "Limpeza semanal precisa fechar com evidência (foto ou confirmação humana).",
    status: "active",
    last_violation_at: "2026-05-15",
    policy_id: "policy.human.routine_required",
  },
  {
    id: "en_router_unobstructed",
    rule: "Roteador deve estar desobstruído para evitar wifi intermitente.",
    status: "violated",
    last_violation_at: "2026-05-19",
  },
];

export const STUB_RUNTIMES: RuntimeRecord[] = [
  {
    id: "rt_minilab_agent_lab8gb",
    name: "minilab-agent",
    machine_id: "lab-8gb",
    version: "0.3.1",
    state: "running",
    critical: true,
    last_used_at: "2026-05-19 09:00",
    config_groups: [
      {
        label: "service",
        entries: [
          { key: "boot", value: "on" },
          { key: "log_level", value: "info" },
        ],
      },
    ],
    health: [
      { label: "heartbeat", status: "ok" },
      { label: "log size", status: "ok", detail: "12 MB" },
    ],
    receipt_id: "r_104",
  },
  {
    id: "rt_heartbeat_daemon",
    name: "heartbeat-daemon",
    machine_id: "lab-8gb",
    version: "1.2.0",
    state: "running",
    critical: true,
    last_used_at: "2026-05-19 09:01",
    health: [{ label: "sweep", status: "ok" }],
  },
  {
    id: "rt_ollama_lab512",
    name: "Ollama",
    machine_id: "lab-512",
    version: "0.5.2",
    state: "running",
    critical: true,
    last_used_at: "2026-05-19 09:01",
    config_groups: [
      {
        label: "models",
        entries: [
          { key: "default", value: "local-operator-v1" },
          { key: "cache_path", value: "/var/ollama/cache" },
        ],
      },
    ],
    health: [
      { label: "model cache", status: "warn", detail: "82% cheio" },
      { label: "load avg", status: "ok" },
    ],
    receipt_id: "r_104",
  },
  {
    id: "rt_local_operator",
    name: "local-operator",
    machine_id: "lab-512",
    version: "0.9.0",
    state: "running",
    critical: true,
    last_used_at: "2026-05-19 09:00",
    health: [{ label: "latency", status: "ok", detail: "p95 320ms" }],
    dependencies: ["rt_ollama_lab512"],
  },
  {
    id: "rt_benchmark_runner",
    name: "benchmark-runner",
    machine_id: "lab-512",
    version: "0.1.4",
    state: "installed",
    last_used_at: "2026-05-17 14:00",
    health: [{ label: "idle", status: "ok" }],
  },
  {
    id: "rt_minilab_ui",
    name: "minilab-ui",
    machine_id: "lab-256",
    version: "0.5.0",
    state: "running",
    critical: false,
    last_used_at: "2026-05-19 09:00",
    health: [{ label: "build", status: "ok" }],
    receipt_id: "r_104",
  },
  {
    id: "rt_browser_automation",
    name: "browser-automation",
    machine_id: "lab-256",
    version: "0.2.3",
    state: "needs_update",
    last_used_at: "2026-05-19 08:58",
    health: [
      { label: "session", status: "warn", detail: "wifi intermitente afeta runs" },
    ],
  },
  {
    id: "rt_git",
    name: "git",
    machine_id: "lab-256",
    version: "2.43.0",
    state: "installed",
    last_used_at: "2026-05-19 08:55",
    health: [{ label: "config", status: "ok" }],
  },
  {
    id: "rt_supabase_client",
    name: "supabase client",
    version: "2.39.0",
    state: "running",
    critical: true,
    last_used_at: "2026-05-19 09:00",
    health: [{ label: "auth", status: "ok" }],
    dependencies: [],
  },
  {
    id: "rt_premium_llm_bridge",
    name: "premium-llm-bridge",
    version: "0.0.5",
    state: "broken",
    last_used_at: "2026-05-19 04:10",
    health: [
      { label: "auth", status: "bad", detail: "PREMIUM_LLM_KEY missing" },
    ],
    ghost_id: "g_002",
  },
  {
    id: "rt_observability_collector",
    name: "observability-collector",
    version: "0.4.1",
    state: "planned",
    health: [{ label: "scope", status: "unknown" }],
  },
];
